//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.1
//     from Assets/ShootEmUp/NewInput control/GameplayControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameplayControl: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameplayControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameplayControl"",
    ""maps"": [
        {
            ""name"": ""PlayerControl"",
            ""id"": ""f1baef56-095b-4e0f-b12c-7f57a500ed99"",
            ""actions"": [
                {
                    ""name"": ""A"",
                    ""type"": ""Button"",
                    ""id"": ""4a041f0c-98bb-4a2d-9cd4-d01ca2c37627"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B"",
                    ""type"": ""Button"",
                    ""id"": ""33cfdda6-5450-4b1b-a85c-46092d8c13e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Y"",
                    ""type"": ""Button"",
                    ""id"": ""5073ad41-877e-4165-8d09-118656e2b4ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""X"",
                    ""type"": ""Button"",
                    ""id"": ""d094ba9d-4361-45da-9918-76eb124d22be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D Left"",
                    ""type"": ""Button"",
                    ""id"": ""599213ee-e883-4366-b397-b46be4c4c624"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D Right"",
                    ""type"": ""Button"",
                    ""id"": ""fc6268b1-a506-475c-b6de-4ffdb70add59"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D Up"",
                    ""type"": ""Button"",
                    ""id"": ""dbfcb722-c561-418e-ae39-fbf5f5a083c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D Down"",
                    ""type"": ""Button"",
                    ""id"": ""b35cee59-9b42-41b6-9370-249ac0fefe21"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""cdb74610-4bc1-440e-be05-f89b3a900236"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jetpack"",
                    ""type"": ""Button"",
                    ""id"": ""8cb5efc5-fe33-4611-ab73-04ca65216f35"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sliding"",
                    ""type"": ""Button"",
                    ""id"": ""8e14aff3-0901-4f1f-9b83-db108c6e8c41"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchGun"",
                    ""type"": ""Button"",
                    ""id"": ""56377042-d0c4-4b97-8903-92cd0f7c2b0e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""344d44f4-0248-4724-b7c1-efece6371fa4"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dcad9655-0594-46c6-9a67-15dd43bbebfd"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04843388-0eb4-4028-952e-44efc974288c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6aba65e-1088-4d89-ace1-d97fc5f9782d"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3c1ea4a-bba1-4d8d-91e9-42ee946949a7"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa7a35db-0ff9-45f2-b4eb-7ccae2f808c3"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be8506c4-9a3d-4c8d-9c54-bb826eb92e17"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d74e880-0de1-452a-b3f0-63ad882d6329"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f498161-a6de-46fa-9f2e-4c3dfe94b8cf"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df8d66ca-13f5-4db6-a562-ee4442799ae6"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc549f7a-c9e0-4adb-80ad-af9640bc54d7"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78139d79-e251-4927-935f-4dafe08c5cfa"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c304d0d-3494-47b2-9cee-f0720a99a8b7"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa686ddf-fd05-48e9-aef5-67a5416f9859"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43b4ede5-2238-4b59-933f-493377385d9a"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a459a83d-2ac5-4619-9a43-4bc7e669ec1a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7c55792-4152-404a-93c8-2ddda295920f"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87ef4220-6e56-4b1e-b739-6051ef8a18dc"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff6045a2-2c41-42fa-b0fc-289605a40d9e"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83acc2df-b713-4da3-94fa-9235de23cd72"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jetpack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6a5f205-9de8-4c66-b477-5d75b931240a"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jetpack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8b24154-57b1-4b86-850a-1bea0d0c8896"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sliding"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""113beea4-9b87-4c11-9d0f-f87e8ca5eb83"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sliding"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6765f288-9324-4c9e-9c2e-2c475aa09a0d"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerControl
        m_PlayerControl = asset.FindActionMap("PlayerControl", throwIfNotFound: true);
        m_PlayerControl_A = m_PlayerControl.FindAction("A", throwIfNotFound: true);
        m_PlayerControl_B = m_PlayerControl.FindAction("B", throwIfNotFound: true);
        m_PlayerControl_Y = m_PlayerControl.FindAction("Y", throwIfNotFound: true);
        m_PlayerControl_X = m_PlayerControl.FindAction("X", throwIfNotFound: true);
        m_PlayerControl_DLeft = m_PlayerControl.FindAction("D Left", throwIfNotFound: true);
        m_PlayerControl_DRight = m_PlayerControl.FindAction("D Right", throwIfNotFound: true);
        m_PlayerControl_DUp = m_PlayerControl.FindAction("D Up", throwIfNotFound: true);
        m_PlayerControl_DDown = m_PlayerControl.FindAction("D Down", throwIfNotFound: true);
        m_PlayerControl_Pause = m_PlayerControl.FindAction("Pause", throwIfNotFound: true);
        m_PlayerControl_Jetpack = m_PlayerControl.FindAction("Jetpack", throwIfNotFound: true);
        m_PlayerControl_Sliding = m_PlayerControl.FindAction("Sliding", throwIfNotFound: true);
        m_PlayerControl_SwitchGun = m_PlayerControl.FindAction("SwitchGun", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerControl
    private readonly InputActionMap m_PlayerControl;
    private List<IPlayerControlActions> m_PlayerControlActionsCallbackInterfaces = new List<IPlayerControlActions>();
    private readonly InputAction m_PlayerControl_A;
    private readonly InputAction m_PlayerControl_B;
    private readonly InputAction m_PlayerControl_Y;
    private readonly InputAction m_PlayerControl_X;
    private readonly InputAction m_PlayerControl_DLeft;
    private readonly InputAction m_PlayerControl_DRight;
    private readonly InputAction m_PlayerControl_DUp;
    private readonly InputAction m_PlayerControl_DDown;
    private readonly InputAction m_PlayerControl_Pause;
    private readonly InputAction m_PlayerControl_Jetpack;
    private readonly InputAction m_PlayerControl_Sliding;
    private readonly InputAction m_PlayerControl_SwitchGun;
    public struct PlayerControlActions
    {
        private @GameplayControl m_Wrapper;
        public PlayerControlActions(@GameplayControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @A => m_Wrapper.m_PlayerControl_A;
        public InputAction @B => m_Wrapper.m_PlayerControl_B;
        public InputAction @Y => m_Wrapper.m_PlayerControl_Y;
        public InputAction @X => m_Wrapper.m_PlayerControl_X;
        public InputAction @DLeft => m_Wrapper.m_PlayerControl_DLeft;
        public InputAction @DRight => m_Wrapper.m_PlayerControl_DRight;
        public InputAction @DUp => m_Wrapper.m_PlayerControl_DUp;
        public InputAction @DDown => m_Wrapper.m_PlayerControl_DDown;
        public InputAction @Pause => m_Wrapper.m_PlayerControl_Pause;
        public InputAction @Jetpack => m_Wrapper.m_PlayerControl_Jetpack;
        public InputAction @Sliding => m_Wrapper.m_PlayerControl_Sliding;
        public InputAction @SwitchGun => m_Wrapper.m_PlayerControl_SwitchGun;
        public InputActionMap Get() { return m_Wrapper.m_PlayerControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControlActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerControlActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerControlActionsCallbackInterfaces.Add(instance);
            @A.started += instance.OnA;
            @A.performed += instance.OnA;
            @A.canceled += instance.OnA;
            @B.started += instance.OnB;
            @B.performed += instance.OnB;
            @B.canceled += instance.OnB;
            @Y.started += instance.OnY;
            @Y.performed += instance.OnY;
            @Y.canceled += instance.OnY;
            @X.started += instance.OnX;
            @X.performed += instance.OnX;
            @X.canceled += instance.OnX;
            @DLeft.started += instance.OnDLeft;
            @DLeft.performed += instance.OnDLeft;
            @DLeft.canceled += instance.OnDLeft;
            @DRight.started += instance.OnDRight;
            @DRight.performed += instance.OnDRight;
            @DRight.canceled += instance.OnDRight;
            @DUp.started += instance.OnDUp;
            @DUp.performed += instance.OnDUp;
            @DUp.canceled += instance.OnDUp;
            @DDown.started += instance.OnDDown;
            @DDown.performed += instance.OnDDown;
            @DDown.canceled += instance.OnDDown;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Jetpack.started += instance.OnJetpack;
            @Jetpack.performed += instance.OnJetpack;
            @Jetpack.canceled += instance.OnJetpack;
            @Sliding.started += instance.OnSliding;
            @Sliding.performed += instance.OnSliding;
            @Sliding.canceled += instance.OnSliding;
            @SwitchGun.started += instance.OnSwitchGun;
            @SwitchGun.performed += instance.OnSwitchGun;
            @SwitchGun.canceled += instance.OnSwitchGun;
        }

        private void UnregisterCallbacks(IPlayerControlActions instance)
        {
            @A.started -= instance.OnA;
            @A.performed -= instance.OnA;
            @A.canceled -= instance.OnA;
            @B.started -= instance.OnB;
            @B.performed -= instance.OnB;
            @B.canceled -= instance.OnB;
            @Y.started -= instance.OnY;
            @Y.performed -= instance.OnY;
            @Y.canceled -= instance.OnY;
            @X.started -= instance.OnX;
            @X.performed -= instance.OnX;
            @X.canceled -= instance.OnX;
            @DLeft.started -= instance.OnDLeft;
            @DLeft.performed -= instance.OnDLeft;
            @DLeft.canceled -= instance.OnDLeft;
            @DRight.started -= instance.OnDRight;
            @DRight.performed -= instance.OnDRight;
            @DRight.canceled -= instance.OnDRight;
            @DUp.started -= instance.OnDUp;
            @DUp.performed -= instance.OnDUp;
            @DUp.canceled -= instance.OnDUp;
            @DDown.started -= instance.OnDDown;
            @DDown.performed -= instance.OnDDown;
            @DDown.canceled -= instance.OnDDown;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Jetpack.started -= instance.OnJetpack;
            @Jetpack.performed -= instance.OnJetpack;
            @Jetpack.canceled -= instance.OnJetpack;
            @Sliding.started -= instance.OnSliding;
            @Sliding.performed -= instance.OnSliding;
            @Sliding.canceled -= instance.OnSliding;
            @SwitchGun.started -= instance.OnSwitchGun;
            @SwitchGun.performed -= instance.OnSwitchGun;
            @SwitchGun.canceled -= instance.OnSwitchGun;
        }

        public void RemoveCallbacks(IPlayerControlActions instance)
        {
            if (m_Wrapper.m_PlayerControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerControlActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerControlActions @PlayerControl => new PlayerControlActions(this);
    public interface IPlayerControlActions
    {
        void OnA(InputAction.CallbackContext context);
        void OnB(InputAction.CallbackContext context);
        void OnY(InputAction.CallbackContext context);
        void OnX(InputAction.CallbackContext context);
        void OnDLeft(InputAction.CallbackContext context);
        void OnDRight(InputAction.CallbackContext context);
        void OnDUp(InputAction.CallbackContext context);
        void OnDDown(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnJetpack(InputAction.CallbackContext context);
        void OnSliding(InputAction.CallbackContext context);
        void OnSwitchGun(InputAction.CallbackContext context);
    }
}
